export const mockChats = [
    {
      id: 1,
      messages: [
        { role: 'user', content: 'What is React?' },
        { role: 'assistant', content: 'React is a popular JavaScript library for building user interfaces.' },
      ],
    },
    {
      id: 2,
      messages: [
        { role: 'user', content: 'Is Python good for beginners?' },
        { role: 'assistant', content: 'Yes, Python is often recommended for beginners due to its simplicity and readability.' },
      ],
    },
  ];
  
  export function mockChatGPTResponse(input) {
    return {
      role: 'assistant',
      content: `This is a mock response to: "${input}". In a real application, this would be generated by the ChatGPT API.`,
    };
  }